version: '3.5'
services:
  node:
    image: 'node:10-alpine'
    ports:
      - 8081:8080
      - 8889:8888
    working_dir: /app
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    command: sh -c "yarn && npm run start"
volumes:
  node_modules:
